"""tabel skor SEPI dan TSI

Revision ID: 037b20fdbbfa
Revises: b31f5c9a7e42
Create Date: 2026-09-10 17:02:34.404868
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


revision: str = '037b20fdbbfa'
down_revision: Union[str, None] = 'b31f5c9a7e42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('station_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.Column('sepi', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('raw_t', sa.Float(), nullable=False),
    sa.Column('raw_e', sa.Float(), nullable=True),
    sa.Column('raw_a', sa.Float(), nullable=False),
    sa.Column('raw_u', sa.Float(), nullable=False),
    sa.Column('raw_c', sa.Float(), nullable=True),
    sa.Column('line_count', sa.Integer(), nullable=False),
    sa.Column('halte_count', sa.Integer(), nullable=False),
    sa.Column('other_mode_count', sa.Integer(), nullable=False),
    sa.Column('area_km2', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_station_scores_minutes_rank', 'station_scores', ['minutes', 'rank'], unique=False)
    op.create_index(op.f('ix_station_scores_station_id'), 'station_scores', ['station_id'], unique=False)
    op.create_table('tenant_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('tsi', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('demand', sa.Integer(), nullable=False),
    sa.Column('connectivity', sa.Float(), nullable=False),
    sa.Column('supply', sa.Integer(), nullable=False),
    sa.Column('headroom', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_scores_category'), 'tenant_scores', ['category'], unique=False)
    op.create_index('ix_tenant_scores_lookup', 'tenant_scores', ['station_id', 'minutes', 'tsi'], unique=False)
    op.create_index('ix_tenant_scores_rank', 'tenant_scores', ['category', 'minutes', 'rank'], unique=False)
    op.create_index(op.f('ix_tenant_scores_station_id'), 'tenant_scores', ['station_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenant_scores_station_id'), table_name='tenant_scores')
    op.drop_index('ix_tenant_scores_rank', table_name='tenant_scores')
    op.drop_index('ix_tenant_scores_lookup', table_name='tenant_scores')
    op.drop_index(op.f('ix_tenant_scores_category'), table_name='tenant_scores')
    op.drop_table('tenant_scores')
    op.drop_index(op.f('ix_station_scores_station_id'), table_name='station_scores')
    op.drop_index('ix_station_scores_minutes_rank', table_name='station_scores')
    op.drop_table('station_scores')
    # ### end Alembic commands ###
