"""pisahkan SEPI dari TOPSIS, tambah kelas dan confidence

Revision ID: 2fe9c7b6304b
Revises: 037b20fdbbfa
Create Date: 2026-09-10 18:15:49.216365
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


revision: str = '2fe9c7b6304b'
down_revision: Union[str, None] = '037b20fdbbfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Baris lama WAJIB dibuang, bukan sekadar demi kemudahan menambah kolom
    # NOT NULL. Sebelum revisi ini kolom `sepi` diisi kedekatan TOPSIS x 100;
    # menurut definisi baru (jumlah berbobot, lihat scoring/sepi.py) seluruh 46
    # baris itu tidak sah. Membiarkannya lalu menambal kolom baru akan
    # menghasilkan tabel yang separuh isinya angka jenis lama tanpa penanda apa
    # pun - persis cara kekeliruan bertahan hidup.
    #
    # Aman dilakukan karena station_scores sepenuhnya data turunan: bisa
    # dibangun ulang kapan saja dengan
    #     python -m scripts.compute_sepi --minutes 10
    op.execute("DELETE FROM station_scores")

    op.add_column("station_scores", sa.Column("kelas", sa.String(), nullable=False))
    op.add_column("station_scores", sa.Column("keputusan", sa.String(), nullable=False))
    op.add_column("station_scores", sa.Column("topsis", sa.Float(), nullable=False))
    op.add_column(
        "station_scores", sa.Column("variabel_terpakai", sa.Integer(), nullable=False)
    )
    op.add_column("station_scores", sa.Column("confidence", sa.Float(), nullable=False))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('station_scores', 'confidence')
    op.drop_column('station_scores', 'variabel_terpakai')
    op.drop_column('station_scores', 'topsis')
    op.drop_column('station_scores', 'keputusan')
    op.drop_column('station_scores', 'kelas')
    # ### end Alembic commands ###
