"""activity chain and station objects

Revision ID: 8e28c27f6231
Revises: d4a7fc2da6ce
Create Date: 2026-09-07 21:36:52.095960
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

revision: str = '8e28c27f6231'
down_revision: Union[str, None] = 'd4a7fc2da6ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_raw',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_kind', sa.String(), nullable=False),
    sa.Column('source_ref', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('payload_hash', sa.String(), nullable=False),
    sa.Column('gate_status', sa.String(), nullable=False),
    sa.Column('gate_reason', sa.String(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("gate_status IN ('pending', 'passed', 'rejected')", name='ck_activity_raw_gate_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payload_hash', name='uq_activity_raw_hash')
    )
    op.create_table('station_zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('zone_type', sa.String(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('area_m2', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('station_id', 'name', name='uq_station_zone_name')
    )
    op.create_index(op.f('ix_station_zones_station_id'), 'station_zones', ['station_id'], unique=False)
    op.create_index(op.f('ix_station_zones_zone_type'), 'station_zones', ['zone_type'], unique=False)
    op.create_table('activity_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=True),
    sa.Column('isochrone_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('narrative', sa.Text(), nullable=False),
    sa.Column('photo_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('provenance', sa.String(), nullable=True),
    sa.Column('has_interviewer_pattern', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['isochrone_id'], ['isochrones.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['raw_id'], ['activity_raw.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('raw_id')
    )
    op.create_index(op.f('ix_activity_points_category'), 'activity_points', ['category'], unique=False)
    op.create_index(op.f('ix_activity_points_isochrone_id'), 'activity_points', ['isochrone_id'], unique=False)
    op.create_index(op.f('ix_activity_points_station_id'), 'activity_points', ['station_id'], unique=False)
    op.create_table('tenant_clusters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('dominant_category', sa.String(), nullable=True),
    sa.Column('unit_total', sa.Integer(), nullable=False),
    sa.Column('unit_filled', sa.Integer(), nullable=False),
    sa.Column('unit_empty', sa.Integer(), nullable=False),
    sa.Column('radius_m', sa.Float(), nullable=True),
    sa.Column('criteria_note', sa.Text(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['station_zones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_clusters_station_id'), 'tenant_clusters', ['station_id'], unique=False)
    op.create_index(op.f('ix_tenant_clusters_zone_id'), 'tenant_clusters', ['zone_id'], unique=False)
    op.create_table('activity_extractions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_point_id', sa.Integer(), nullable=False),
    sa.Column('archetype', sa.String(), nullable=True),
    sa.Column('archetype_probs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('brands', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sentiment_label', sa.String(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('spatially_validated', sa.Boolean(), nullable=False),
    sa.Column('validation_note', sa.Text(), nullable=True),
    sa.Column('model_versions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['activity_point_id'], ['activity_points.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('activity_point_id')
    )
    op.create_index(op.f('ix_activity_extractions_archetype'), 'activity_extractions', ['archetype'], unique=False)
    op.create_table('ad_spots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('activity_point_id', sa.Integer(), nullable=True),
    sa.Column('media_type', sa.String(), nullable=True),
    sa.Column('media_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('visibility_note', sa.Text(), nullable=True),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('terpakai', 'kosong')", name='ck_ad_spot_status'),
    sa.CheckConstraint('media_count >= 0', name='ck_ad_spot_media_count'),
    sa.ForeignKeyConstraint(['activity_point_id'], ['activity_points.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['station_zones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ad_spots_station_id'), 'ad_spots', ['station_id'], unique=False)
    op.create_index(op.f('ix_ad_spots_zone_id'), 'ad_spots', ['zone_id'], unique=False)
    op.create_table('crowd_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_point_id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=True),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('time_window', sa.String(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('respondent_ref', sa.String(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("time_window IN ('pagi', 'siang', 'sore')", name='ck_crowd_rating_time_window'),
    sa.CheckConstraint('rating BETWEEN 1 AND 5', name='ck_crowd_rating_range'),
    sa.ForeignKeyConstraint(['activity_point_id'], ['activity_points.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['zone_id'], ['station_zones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crowd_ratings_activity_point_id'), 'crowd_ratings', ['activity_point_id'], unique=False)
    op.create_index(op.f('ix_crowd_ratings_station_id'), 'crowd_ratings', ['station_id'], unique=False)
    op.create_index(op.f('ix_crowd_ratings_zone_id'), 'crowd_ratings', ['zone_id'], unique=False)
    op.create_table('facility_issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('activity_point_id', sa.Integer(), nullable=True),
    sa.Column('issue_type', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('spatially_validated', sa.Boolean(), nullable=False),
    sa.Column('validation_note', sa.Text(), nullable=True),
    sa.Column('still_present', sa.Boolean(), nullable=True),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['activity_point_id'], ['activity_points.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['station_zones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facility_issues_issue_type'), 'facility_issues', ['issue_type'], unique=False)
    op.create_index(op.f('ix_facility_issues_station_id'), 'facility_issues', ['station_id'], unique=False)
    op.create_index(op.f('ix_facility_issues_zone_id'), 'facility_issues', ['zone_id'], unique=False)
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('cluster_id', sa.Integer(), nullable=True),
    sa.Column('activity_point_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('distance_to_gate_m', sa.Float(), nullable=True),
    sa.Column('distance_to_platform_m', sa.Float(), nullable=True),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('aktif', 'tutup', 'kosong')", name='ck_tenant_status'),
    sa.ForeignKeyConstraint(['activity_point_id'], ['activity_points.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cluster_id'], ['tenant_clusters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['station_zones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_category'), 'tenants', ['category'], unique=False)
    op.create_index(op.f('ix_tenants_cluster_id'), 'tenants', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_tenants_station_id'), 'tenants', ['station_id'], unique=False)
    op.create_index(op.f('ix_tenants_zone_id'), 'tenants', ['zone_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenants_zone_id'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_station_id'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_cluster_id'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_category'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_facility_issues_zone_id'), table_name='facility_issues')
    op.drop_index(op.f('ix_facility_issues_station_id'), table_name='facility_issues')
    op.drop_index(op.f('ix_facility_issues_issue_type'), table_name='facility_issues')
    op.drop_table('facility_issues')
    op.drop_index(op.f('ix_crowd_ratings_zone_id'), table_name='crowd_ratings')
    op.drop_index(op.f('ix_crowd_ratings_station_id'), table_name='crowd_ratings')
    op.drop_index(op.f('ix_crowd_ratings_activity_point_id'), table_name='crowd_ratings')
    op.drop_table('crowd_ratings')
    op.drop_index(op.f('ix_ad_spots_zone_id'), table_name='ad_spots')
    op.drop_index(op.f('ix_ad_spots_station_id'), table_name='ad_spots')
    op.drop_table('ad_spots')
    op.drop_index(op.f('ix_activity_extractions_archetype'), table_name='activity_extractions')
    op.drop_table('activity_extractions')
    op.drop_index(op.f('ix_tenant_clusters_zone_id'), table_name='tenant_clusters')
    op.drop_index(op.f('ix_tenant_clusters_station_id'), table_name='tenant_clusters')
    op.drop_table('tenant_clusters')
    op.drop_index(op.f('ix_activity_points_station_id'), table_name='activity_points')
    op.drop_index(op.f('ix_activity_points_isochrone_id'), table_name='activity_points')
    op.drop_index(op.f('ix_activity_points_category'), table_name='activity_points')
    op.drop_table('activity_points')
    op.drop_index(op.f('ix_station_zones_zone_type'), table_name='station_zones')
    op.drop_index(op.f('ix_station_zones_station_id'), table_name='station_zones')
    op.drop_table('station_zones')
    op.drop_table('activity_raw')
    # ### end Alembic commands ###
