"""initial schema

Revision ID: d4a7fc2da6ce
Revises: 
Create Date: 2026-09-07 21:27:49.184584
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

revision: str = 'd4a7fc2da6ce'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('osm_type', sa.String(), nullable=False),
    sa.Column('osm_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('osm_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('osm_type', 'osm_id', name='uq_poi_osm')
    )
    op.create_index(op.f('ix_poi_category'), 'poi', ['category'], unique=False)
    op.create_table('stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('types', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('lines', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('served', sa.Boolean(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('kecamatan', sa.String(), nullable=True),
    sa.Column('kabkot', sa.String(), nullable=True),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('area_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('profile', sa.String(), nullable=False),
    sa.Column('office_share', sa.Float(), nullable=True),
    sa.Column('residential_share', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('accessed_at', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('station_id', 'source', name='uq_area_profile_station_source')
    )
    op.create_index(op.f('ix_area_profile_station_id'), 'area_profile', ['station_id'], unique=False)
    op.create_table('isochrones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=True),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('origin_point', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('area_m2', sa.Float(), nullable=True),
    sa.Column('permeability_index', sa.Float(), nullable=True),
    sa.Column('walk_speed_kmh', sa.Float(), nullable=True),
    sa.Column('match_method', sa.String(), nullable=True),
    sa.Column('match_distance_m', sa.Float(), nullable=True),
    sa.Column('source_layer_id', sa.String(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('minutes > 0', name='ck_isochrone_minutes_positive'),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('station_id', 'minutes', name='uq_isochrone_station_minutes')
    )
    op.create_index(op.f('ix_isochrones_station_id'), 'isochrones', ['station_id'], unique=False)
    op.create_table('passenger_volume',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(), nullable=False),
    sa.Column('passengers_per_day', sa.Float(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('accessed_at', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('station_id', 'period', 'source', name='uq_passenger_volume_station_period')
    )
    op.create_index(op.f('ix_passenger_volume_station_id'), 'passenger_volume', ['station_id'], unique=False)
    op.create_table('price_references',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('item_name', sa.String(), nullable=True),
    sa.Column('price_idr', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=True),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('accessed_at', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_references_category'), 'price_references', ['category'], unique=False)
    op.create_index(op.f('ix_price_references_kind'), 'price_references', ['kind'], unique=False)
    op.create_index(op.f('ix_price_references_station_id'), 'price_references', ['station_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_references_station_id'), table_name='price_references')
    op.drop_index(op.f('ix_price_references_kind'), table_name='price_references')
    op.drop_index(op.f('ix_price_references_category'), table_name='price_references')
    op.drop_table('price_references')
    op.drop_index(op.f('ix_passenger_volume_station_id'), table_name='passenger_volume')
    op.drop_table('passenger_volume')
    op.drop_index(op.f('ix_isochrones_station_id'), table_name='isochrones')
    op.drop_table('isochrones')
    op.drop_index(op.f('ix_area_profile_station_id'), table_name='area_profile')
    op.drop_table('area_profile')
    op.drop_table('stations')
    op.drop_index(op.f('ix_poi_category'), table_name='poi')
    op.drop_table('poi')
    # ### end Alembic commands ###
